// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8K8sRfHnl4YYeYXcRo45kNTE1ubnZ3y8',
    appId: '1:476007589290:web:ed39f2767a76758628f7d3',
    messagingSenderId: '476007589290',
    projectId: 'inspireme887',
    authDomain: 'inspireme887.firebaseapp.com',
    storageBucket: 'inspireme887.firebasestorage.app',
    measurementId: 'G-ZM064V3KCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBnmIiy5Clz9XdrIXBQ7X8BTXpXvwhCfo',
    appId: '1:476007589290:android:771c15d1d0fb06a028f7d3',
    messagingSenderId: '476007589290',
    projectId: 'inspireme887',
    storageBucket: 'inspireme887.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADhKPkjHbN8DRVfJ5Vu1gSRNC8dESLa1I',
    appId: '1:476007589290:ios:31a88bad924428e528f7d3',
    messagingSenderId: '476007589290',
    projectId: 'inspireme887',
    storageBucket: 'inspireme887.firebasestorage.app',
    iosBundleId: 'com.example.inspireMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADhKPkjHbN8DRVfJ5Vu1gSRNC8dESLa1I',
    appId: '1:476007589290:ios:31a88bad924428e528f7d3',
    messagingSenderId: '476007589290',
    projectId: 'inspireme887',
    storageBucket: 'inspireme887.firebasestorage.app',
    iosBundleId: 'com.example.inspireMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8K8sRfHnl4YYeYXcRo45kNTE1ubnZ3y8',
    appId: '1:476007589290:web:475d99a4308c4c6628f7d3',
    messagingSenderId: '476007589290',
    projectId: 'inspireme887',
    authDomain: 'inspireme887.firebaseapp.com',
    storageBucket: 'inspireme887.firebasestorage.app',
    measurementId: 'G-XG26YL2NGG',
  );
}
